apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ctiyftruy-java-springboot
  janus-idp.io/tekton: ctiyftruy-java-springboot
  backstage.io/kubernetes-id: ctiyftruy-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ctiyftruy-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
